name: Check the source code
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Check the source code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: rm -rf node_modules && yarn install --frozen-lockfile
      - name: Prettier
        run: yarn format
      - name: Lint
        run: yarn lint
